### ISSUE TITLE
[Enhancement] Border openings

### ISSUE THREAD

**Issue by JbCourtois** [yannikkellerde/GABOR#1]
In addition to the Burgregel opening rule, there is also a Tournament version (available e.g. on https://www.yucata.de) where the first player must open on the border squares.

I'll try to solve the game from these openings.

I think that the first moves are forced: White a3 (or symetrical move) Black b3, which should greatly reduce the search tree.

Proof idea:
- The a1, a2, b1 openings lose to d4
- In the a3 opening, all Black responses other than b3 lose to either b2 or d4.

I conjecture that the result from the a3 opening is a draw, looking forward to check that :-)

**Comment by JbCourtois** [comment]
I think that winhashes can be efficiently used for pruning. It seems that in the current project, they are only used to check wins.

Have you tried, when analyzing a position, to remove the winning patterns that contain both a white stone and a black stone ? So that:
- If square A's winning patterns is a subset of square B's patterns, then neither player should play on A before B
- If only one winning pattern remains on the board, the position can be trivially solved (draw unless the active player immediatly wins with that pattern)

Unfortunately I will be quite busy until August, but after that I will gladly contribute on this project.

**Comment by yannikkellerde** [comment]
Thanks for your suggestions :)
If you mean with winhashes that I delete all nodes from the search tree that have been proven or disproven and only store the hashes, so I don't have to recalculate them again, then I am already using winhashes.
Analyzing the game more in terms of the winning patterns left does actually seem like a great Idea. First, your subset Idea should help prune a few lines, especially as it includes removing/ignoring all free squares that are not associated with any viable winning patterns anymore.
Your other suggestion about trivially solvable endgame positions has given me the Idea of only storing the configuration of viable winning patterns left instead of the whole board for endgame positions. This would make creating a memory efficient endgame tablebase much easier as a single stored configuration covers many different possible board states. Actually I feel like having a 3 or 4 winning pattern endgame table could already be enough to prove the tournament version.

I will probably also only have time to put in a lot of effort into these kinds of projects in my semester break, but with these promising Ideas, I may try to find some free time to get to it earlier.

**Comment by yannikkellerde** [comment]
Just pinging here to let you know that I have solved QANGO with border openings.

**Comment by JbCourtois** [comment]
That's great ! And the tool to view the proofs is really easy to use. Have a star !
